/* Scans a widgets directory and writes registry.js listing every widget id.
   Usage: node scripts/build_registry.mjs [widgetsDir] [outFile]
   Defaults: widgets  ->  widgets/registry.js
   The GitHub Pages deploy runs this so the live site always lists every
   merged widget. Participants never edit registry.js by hand. */
import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = process.argv[2] || "widgets";
const out = process.argv[3] || join(dir, "registry.js");

const ids = readdirSync(dir)
  .filter((f) => f.endsWith(".js") && f !== "registry.js")
  .map((f) => f.slice(0, -3))
  .sort();

writeFileSync(
  out,
  "// AUTO-GENERATED by scripts/build_registry.mjs — do not edit by hand.\n" +
    "window.WORKSHOP_WIDGET_IDS = " + JSON.stringify(ids) + ";\n"
);
console.log(`registry.js written (${ids.length}): ${ids.join(", ") || "(none)"}`);
